### ISSUE TITLE
Issue with SmartTicker Rendering

### ISSUE THREAD

**Issue by MiladSadeghi** [eugen-k/react-smart-ticker#71]
Hi there! I've been using SmartTicker and set it up with the following configuration:

```tsx
<SmartTicker
    smart={false}
    isText={true}
    autoFill={true}
    playOnHover={false}
    pauseOnHover={false}
    playOnClick={false}
    pauseOnClick={false}
    direction={'right'}
    rtl={true}
    infiniteScrollView={true}
    speed={150}
    delay={0}
    iterations={'infinite'}
    disableSelect={true}
>
```

However, I'm encountering an issue where the output looks incorrect, as shown in the attached clip:

https://github.com/user-attachments/assets/edff6bb1-2b01-4284-a26b-7c08389ed5ad

Could you help identify what might be causing this problem? Thanks in advance!

**Comment by eugen-k** [comment]
Hi Milad,
What's inside the `<SmartTicker>` tag? Is it just a text content or a tag with the text?

**Comment by MiladSadeghi** [comment]
> Hi Milad, What's inside the `<SmartTicker>` tag? Is it just a text content or a tag with the text?

its just a text

**Comment by eugen-k** [comment]
I just tested the component with your settings:
`
<div style={{ position: 'absolute', top: '50%', width: '800px' }}>
      <SmartTicker
        smart={false}
        isText={true}
        autoFill={true}
        playOnHover={false}
        pauseOnHover={false}
        playOnClick={false}
        pauseOnClick={false}
        direction={'right'}
        rtl={true}
        infiniteScrollView={true}
        speed={150}
        delay={0}
        iterations={'infinite'}
        disableSelect={true}
      >
چند متن به زبان فارسی
      </SmartTicker>
    </div>
`
It looks like it works correctly. Please check again what might be wrong with your setup.

https://github.com/user-attachments/assets/babf8a84-b8ac-42e1-af03-abbc60b4fc5e

**Comment by eugen-k** [comment]
Hi Milad, were you able to figure out the problem? Can I close the issue?

**Comment by MiladSadeghi** [comment]
Apologies for the delayed response!

Here is the `NowPlaying` component I'm working with:
```tsx
function NowPlaying({ image, title, newsId }: Props) {
  return (
    <Link to={`/news/${newsId}`} className="align-items-center flex w-[350px]">
      <img
        width={100}
        height={70}
        loading="lazy"
        src={image}
        className="rounded-sm"
        alt="track image"
      />
      <div className="my-auto mr-2 w-full overflow-hidden">
        <SmartTicker
          smart={false}
          isText={true}
          autoFill={true}
          playOnHover={false}
          pauseOnHover={false}
          playOnClick={false}
          pauseOnClick={false}
          direction="right"
          rtl={true}
          infiniteScrollView={true}
          speed={150}
          delay={0}
          iterations="infinite"
          disableSelect={true}
        >
          <p className="text-white">{title}</p>
        </SmartTicker>
      </div>
    </Link>
  );
}
```

There’s no local state inside this component (though I manage some state in the parent component using local state and Zustand). However, the behavior still isn’t working as expected, and the previous issue remains unresolved. I encountered a new issue while doing further development on my app. Also, I implemented the marquee effect using only Tailwind, without any external package. I saw your response, and I realized I need to fix the problem.

This is new mess:
https://github.com/user-attachments/assets/c22cb2b9-7bf8-47b5-813f-fb6178a4b566

In the parent component, I have an audio player. When I pause the audio, the output looks like this:
https://github.com/user-attachments/assets/5c34f0a5-7205-4e88-a92d-ba92d1790a04

**Comment by eugen-k** [comment]
The problem is the <p> tag that is a block element by its nature. So when the component is trying to get the size of the text (to know if it fits or not), the size is always equal to the full width of the block.  I'm going to add a "className" param to a ticker so it will be possible to pass a CSS class name to a ticker. But for now, I would suggest removing <p> tag and placing just the `{title}` as a <SmartTicker> child. The styles should be moved into the "style" parameter, like this:
```
<SmartTicker
          smart={false}
          isText={true}
          autoFill={true}
          playOnHover={false}
          pauseOnHover={false}
          playOnClick={false}
          pauseOnClick={false}
          direction="right"
          rtl={true}
          infiniteScrollView={true}
          speed={150}
          delay={0}
          iterations="infinite"
          disableSelect={true}
          style={{color: "FFF"}}
        >
          {title}
        </SmartTicker>
```

**Comment by MiladSadeghi** [comment]
Okay, thanks! What about the earlier issue? That one didn’t display like a marquee. Here’s the current situation:
https://github.com/user-attachments/assets/025b4ff6-6e6e-4d56-839f-a5371e80e00f

**Comment by eugen-k** [comment]
I'm not able to figure out the problem on just a screen record, but I would assume that the problem is that your `{title}` is changing (despite the text being the same) whenever you press pause. Use the `useMemo` hook in this case so as not to reload the component animation.

**Comment by MiladSadeghi** [comment]
I removed `flex-end` from the `ticker-container`, and now it looks like this!:

https://github.com/user-attachments/assets/8525cb4f-74e4-4f5d-9744-b7166e5815db

**Comment by eugen-k** [comment]
> I changed `flex-end` to `flex-start` from the `ticker-container`, and now it looks like this!:
> 
>  Screen.Recording.2024-10-05.092444.mp4 
> The next question is, how can I manage the spacing between the texts?

I am unsure how changing `flex-end` to `flex-start` makes it work. "Flex-end" is required for the RTL text. I have a guess that your text inside the ticker is wrapped into something else, but anyway, if it works...
You always can test the ticker using this [demo](https://eugen-k.github.io/react-smart-ticker-demo/). Insert your original text in the options, and check. And please let me know if something doesn't work there.

To add a gap between the texts you could insert a non-breaking space: `&nbsp;` or with your OS hotkey.

**Comment by MiladSadeghi** [comment]
I'd like to close this issue with an explanation of the problems I encountered and how I resolved them:

Initially, I mentioned that using `flex-start` seemed to fix the issue, but I ran into another problem. When I had multiple `SmartTicker` components, things got weird—it stopped working! Even after removing the second `SmartTicker` component from another part of the app, the issue persisted. I was using `containerStyle`, so to fix this, I switched to Tailwind and set `flex-start` for the first child of a wrapper like this: `[&>*:first-child]:!justify-start`.

My app is a player, and I store the audio progress time in a Zustand store (I know, bad idea xD). This caused the animation to reset every time the progress updated. To fix it, I split the Zustand store into two: one for the player and one for the audio. This resolved the issue.

Another issue was the space between the texts. I couldn't find any way to create space between texts because when I added a Unicode character, it reset the animation.

In the end, due to the spacing issue, I had to switch to a different marquee package. It's a newly released third-party package, but it seems solid. I would recommend this package to anyone who needs a marquee-like solution—it's really useful!

**Comment by eugen-k** [comment]
I wanted to let you know that the problem with the animation resetting has been addressed in the latest release of react-smart-ticker. You should no longer experience interruptions in the animation caused by frequent updates (like those from state changes in Zustand or similar libraries).

Regarding the spacing issue, the best way to add spacing between texts in the ticker is to include whitespace directly within the content. Since the ticker node content can be a simple inline text node, applying margins or padding isn’t appropriate and could interfere with the flow of the animation. 

Lastly, it’s great to hear you’ve found a workaround with another package, but I hope the updates in react-smart-ticker will make it a viable option for your future projects. If you run into any other issues or have feature requests, feel free to open another issue — I'm always looking to improve!

Thanks again for your feedback and for trying my library!
